jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  mode: NORMAL
  numExecutors: 1
  quietPeriod: 5
  securityRealm:
    local:
      allowsSignup: false
  remotingSecurity:
    enabled: true
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

      unclassified:
  location:
    url: https://079f55ddbeea.ngrok.io/github-webhook/

    tool:
  git:
    installations:
      - home: "git"
        name: "Default"
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: "docker-pass-id"
          username: "fontecilla"
          password: "x"
      domain:
        name: "dockerhub.com"
        description: "DockerHub"
jobs:
  - script: >
      pipelineJob('cookingapp') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                      git {
                          remote
                            {
                              url 'https://github.com/diegofontecilla/cookingWeb'
                            }
                          branch '*/master'
                          extensions {}
                      }
                  }
              }
          }
      }

