pipeline {
    agent any
    stages {
        stage('Smoke test') {
              steps {
                sh 'docker-entrypoint.sh'
            }
        }
        // stage('Build image') {
        //     app = docker.build("fontecilla/cookingapp")
        // }
        // stage('Push image') {
        //     docker.withRegistry('https://hub.docker.com/', 'docker-hub-credentials') {
        //     app.push("${env.BUILD_NUMBER}")
        //     app.push("latest")
        // }
    }
}