pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Running build automation'
                sh './jenkins/scripts/build.sh'
            }
        }
    }
}