pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Running build automation'
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'docker run -v $PWD:/e2e -w /e2e cypress/included:3.4.0'
                sh 'npm test'
            }
        }
    }
}